### ISSUE TITLE
Seems not to play nice with Linux?

### ISSUE THREAD

**Issue by jjohare** [xXAdonesXx/NodeGPT#12]
I tried a git clone and manual requirements install, and a manager install. Same error with the repo's workflow json in both respects

Loading aborted due to error reloading workflow data

TypeError: widget[GET_CONFIG] is not a function
TypeError: widget[GET_CONFIG] is not a function
    at #onFirstConnection (http://serverip/extensions/core/widgetInputs.js:389:54)
    at PrimitiveNode.onAfterGraphConfigured (http://serverip/extensions/core/widgetInputs.js:318:29)
    at app.graph.onConfigure (http://serverip/scripts/app.js:1221:34)
    at LGraph.configure (http://serverip/lib/litegraph.core.js:2260:9)
    at LGraph.configure (http://serverip/scripts/app.js:1201:22)
    at ComfyApp.loadGraphData (http://serverip/scripts/app.js:1451:15)
    at ComfyApp.setup (http://serverip/scripts/app.js:1298:10)
    at async http://serverip/:14:4
This may be due to the following script:
/extensions/core/widgetInputs.js

**Comment by fxtoofaan** [comment]
i am getting same error. 

Loading aborted due to error reloading workflow data

TypeError: widget[GET_CONFIG] is not a function
TypeError: widget[GET_CONFIG] is not a function
    at #onFirstConnection (http://127.0.0.1:8188/extensions/core/widgetInputs.js:389:54)
    at PrimitiveNode.onAfterGraphConfigured (http://127.0.0.1:8188/extensions/core/widgetInputs.js:318:29)
    at app.graph.onConfigure (http://127.0.0.1:8188/scripts/app.js:1221:34)
    at LGraph.configure (http://127.0.0.1:8188/lib/litegraph.core.js:2260:9)
    at LGraph.configure (http://127.0.0.1:8188/scripts/app.js:1201:22)
    at ComfyApp.loadGraphData (http://127.0.0.1:8188/scripts/app.js:1451:15)
    at ComfyApp.setup (http://127.0.0.1:8188/scripts/app.js:1298:10)
    at async http://127.0.0.1:8188/:14:4
This may be due to the following script:
/extensions/core/widgetInputs.js

**Comment by xXAdonesXx** [comment]
Yeah. I only tested it on windows. I think the problem is the sketchy import of autogen I used in the scripts. 

base_dir = os.path.dirname(os.path.abspath(__file__))
parent_dir = os.path.dirname(base_dir)
venv_site_packages = os.path.join(parent_dir, 'venv', 'Lib', 'site-packages')
sys.path.append(venv_site_packages)
import autogen

You may have to install autogen via pip install in some other directory and delete the code above in almost every script. Then you should write ther insted  something like tihs:

sys.path.append("Your Path to the site-packages where autogen is installed")
import autogen

I only would recomend the changes if you really want to use the nodes, because it would get reset every time you update the nodes. I am not a professional programmer, so i do not know how to get this working in other ways yet. If someone knows how I can make this the right way, I would be happy to hear the solution or a pull request.

**Comment by jjohare** [comment]
working on it now.

**Comment by jjohare** [comment]
Apologies, I closed this by mistake it seems  :)

**Comment by jjohare** [comment]
Fine now I think.
