### ISSUE TITLE
ModuleNotFoundError: No module named 'NodeGPT.Output2String'

### ISSUE THREAD

**Issue by dreamrec** [xXAdonesXx/NodeGPT#13]
hi  / i get this error 

i've fallowed the steps for installation , but i'm getting the red nodes all the time.

### ComfyUI Revision: 1595 [f1062be6] | Released on '2023-10-20'
Traceback (most recent call last):
  File "V:\comfyui portable\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "V:\comfyui portable\ComfyUI_windows_portable\ComfyUI\custom_nodes\NodeGPT\__init__.py", line 32, in <module>
    imported_module = importlib.import_module(".{}".format(module_name), __name__)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'NodeGPT.Output2String'

Cannot import V:\comfyui portable\ComfyUI_windows_portable\ComfyUI\custom_nodes\NodeGPT module for custom nodes: No module named 'NodeGPT.Output2String'

Import times for custom nodes:
   0.0 seconds: V:\comfyui portable\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.4 seconds: V:\comfyui portable\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.4 seconds (IMPORT FAILED): V:\comfyui portable\ComfyUI_windows_portable\ComfyUI\custom_nodes\NodeGPT
   0.5 seconds: V:\comfyui portable\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Starting server

**Comment by dreamrec** [comment]
TypeError: widget[GET_CONFIG] is not a function
    at #onFirstConnection (http://127.0.0.1:8188/extensions/core/widgetInputs.js:389:54)
    at PrimitiveNode.onAfterGraphConfigured (http://127.0.0.1:8188/extensions/core/widgetInputs.js:318:29)
    at app.graph.onConfigure (http://127.0.0.1:8188/scripts/app.js:1221:34)
    at LGraph.configure (http://127.0.0.1:8188/lib/litegraph.core.js:2260:9)
    at LGraph.configure (http://127.0.0.1:8188/scripts/app.js:1201:22)
    at ComfyApp.loadGraphData (http://127.0.0.1:8188/scripts/app.js:1451:15)
    at ComfyApp.setup (http://127.0.0.1:8188/scripts/app.js:1298:10)
    at async http://127.0.0.1:8188/:14:4
