### ISSUE TITLE
Startup Error

### ISSUE THREAD

**Issue by Numb94** [xXAdonesXx/NodeGPT#14]
Traceback (most recent call last):
  File "D:\dev\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1734, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\dev\ComfyUI_windows_portable\ComfyUI\custom_nodes\NodeGPT\__init__.py", line 32, in <module>
    imported_module = importlib.import_module(".{}".format(module_name), __name__)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\dev\ComfyUI_windows_portable\ComfyUI\custom_nodes\NodeGPT\Agents\Assistant.py", line 7, in <module>
    import autogen
ModuleNotFoundError: No module named 'autogen'

Cannot import D:\dev\ComfyUI_windows_portable\ComfyUI\custom_nodes\NodeGPT module for custom nodes: No module named 'autogen'

Import times for custom nodes:
   0.0 seconds: D:\dev\ComfyUI_windows_portable\ComfyUI\custom_nodes\Zho_Main_Nodes_Chinese.py
   0.0 seconds (IMPORT FAILED): D:\dev\ComfyUI_windows_portable\ComfyUI\custom_nodes\NodeGPT

**Comment by xXAdonesXx** [comment]
Seems that autogen didn't install properly. Have you run the installer.bat inside the terminal in the folder NodeGPT? Then you should have a venv folder in the NodeGPT folder. After that you have to pip install -r requirements.txt or just pip install pyautogen (inside the activated venv)
If this didn't work it has probably to do something with the import of autogen in every Skript (see the issue for Linux users)

**Comment by Numb94** [comment]
There is a problem with install.bat, just run the commands in install in a separate terminal.

**Comment by Numb94** [comment]
Now Queue prompt reports an error


To see the GUI go to: http://127.0.0.1:8188
got prompt
<autogen.agentchat.assistant_agent.AssistantAgent object at 0x000002D4008F9810>
User (to assistant):

Task here

--------------------------------------------------------------------------------
!!! Exception during processing !!!
Traceback (most recent call last):
  File "D:\dev\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\dev\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\dev\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\dev\ComfyUI_windows_portable\ComfyUI\custom_nodes\NodeGPT\Chat.py", line 46, in execute
    user_object.initiate_chat(
  File "D:\dev\ComfyUI_windows_portable\ComfyUI\custom_nodes\NodeGPT\venv\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 531, in initiate_chat
    self.send(self.generate_init_message(**context), recipient, silent=silent)
  File "D:\dev\ComfyUI_windows_portable\ComfyUI\custom_nodes\NodeGPT\venv\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 334, in send
    recipient.receive(message, self, request_reply, silent)
  File "D:\dev\ComfyUI_windows_portable\ComfyUI\custom_nodes\NodeGPT\venv\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 462, in receive
    reply = self.generate_reply(messages=self.chat_messages[sender], sender=sender)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\dev\ComfyUI_windows_portable\ComfyUI\custom_nodes\NodeGPT\venv\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 781, in generate_reply
    final, reply = reply_func(self, messages=messages, sender=sender, config=reply_func_tuple["config"])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\dev\ComfyUI_windows_portable\ComfyUI\custom_nodes\NodeGPT\venv\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 606, in generate_oai_reply
    response = oai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\dev\ComfyUI_windows_portable\ComfyUI\custom_nodes\NodeGPT\venv\Lib\site-packages\autogen\oai\completion.py", line 799, in create
    response = cls.create(
               ^^^^^^^^^^^
  File "D:\dev\ComfyUI_windows_portable\ComfyUI\custom_nodes\NodeGPT\venv\Lib\site-packages\autogen\oai\completion.py", line 830, in create
    return cls._get_response(params, raise_on_ratelimit_or_timeout=raise_on_ratelimit_or_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\dev\ComfyUI_windows_portable\ComfyUI\custom_nodes\NodeGPT\venv\Lib\site-packages\autogen\oai\completion.py", line 269, in _get_response
    cls._book_keeping(config, response)
  File "D:\dev\ComfyUI_windows_portable\ComfyUI\custom_nodes\NodeGPT\venv\Lib\site-packages\autogen\oai\completion.py", line 168, in _book_keeping
    key = get_key(messages + [choice["message"] for choice in response["choices"]])
                                                              ~~~~~~~~^^^^^^^^^^^
KeyError: 'choices'

Prompt executed in 2.98 seconds

**Comment by Romanio1997** [comment]
llama-cpp installed
All packages from requirements.txt are installed and up to date.
[comfy_mtb] | INFO -> loaded 94 nodes successfuly
[comfy_mtb] | INFO -> Some nodes (2) could not be loaded. This can be ignored, but go to http://127.0.0.1:8188/mtb if you want more information.
C:\AI\ComfyUI_Windows_portable\ComfyUI\custom_nodes\NodeGPT\AutoUpdate.json
Warn!: Traceback (most recent call last):
  File "C:\AI\ComfyUI_Windows_portable\ComfyUI\custom_nodes\NodeGPT\Agents\Assistant.py", line 9, in <module>
    import autogen
  File "C:\AI\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\autogen\__init__.py", line 9, in <module>
    from .agentchat import *
  File "C:\AI\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\autogen\agentchat\__init__.py", line 8, in <module>
    from .assistant_agent import AssistantAgent
  File "C:\AI\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\autogen\agentchat\assistant_agent.py", line 11, in <module>
    from .conversable_agent import ConversableAgent
  File "C:\AI\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 22, in <module>
    from ..code_utils import (
  File "C:\AI\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\autogen\code_utils.py", line 15, in <module>
    import venv
ModuleNotFoundError: No module named 'venv'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\AI\ComfyUI_Windows_portable\ComfyUI\nodes.py", line 2106, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\AI\ComfyUI_Windows_portable\ComfyUI\custom_nodes\NodeGPT\__init__.py", line 127, in <module>
    imported_module = importlib.import_module(".{}".format(module_name), __name__)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\AI\ComfyUI_Windows_portable\ComfyUI\custom_nodes\NodeGPT\Agents\Assistant.py", line 21, in <module>
    import autogen
  File "C:\AI\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\autogen\__init__.py", line 9, in <module>
    from .agentchat import *
  File "C:\AI\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\autogen\agentchat\__init__.py", line 8, in <module>
    from .assistant_agent import AssistantAgent
  File "C:\AI\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\autogen\agentchat\assistant_agent.py", line 11, in <module>
    from .conversable_agent import ConversableAgent
  File "C:\AI\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 22, in <module>
    from ..code_utils import (
  File "C:\AI\ComfyUI_Windows_portable\python_embeded\Lib\site-packages\autogen\code_utils.py", line 15, in <module>
    import venv
ModuleNotFoundError: No module named 'venv'

Warn!: Cannot import C:\AI\ComfyUI_Windows_portable\ComfyUI\custom_nodes\NodeGPT module for custom nodes: No module named 'venv'
