### ISSUE TITLE
import failed. I want to run nodegpt on local lm or ooba but am jammed.

### ISSUE THREAD

**Issue by angrysky56** [xXAdonesXx/NodeGPT#29]
I tried the update.bat

F:\comfyNodeGPT>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
** ComfyUI startup time: 2023-12-12 13:10:18.471906
** Platform: Windows
** Python version: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
** Python executable: F:\comfyNodeGPT\python_embeded\python.exe
** Log path: F:\comfyNodeGPT\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: F:\comfyNodeGPT\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 12288 MB, total RAM 64821 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
### ComfyUI Revision: 1810 [b0aab1e4] | Released on '2023-12-11'
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.jsonF:\comfyNodeGPT\ComfyUI\custom_nodes\NodeGPT\AutoUpdate.json

FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
Traceback (most recent call last):
  File "F:\comfyNodeGPT\ComfyUI\custom_nodes\NodeGPT\API_Nodes\llama-cpp.py", line 9, in <module>
    from llama_cpp import Llama
ModuleNotFoundError: No module named 'llama_cpp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\comfyNodeGPT\ComfyUI\nodes.py", line 1800, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\comfyNodeGPT\ComfyUI\custom_nodes\NodeGPT\__init__.py", line 127, in <module>
    imported_module = importlib.import_module(".{}".format(module_name), __name__)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\comfyNodeGPT\ComfyUI\custom_nodes\NodeGPT\API_Nodes\llama-cpp.py", line 21, in <module>
    from llama_cpp import Llama
ModuleNotFoundError: No module named 'llama_cpp'

Cannot import F:\comfyNodeGPT\ComfyUI\custom_nodes\NodeGPT module for custom nodes: No module named 'llama_cpp'

Import times for custom nodes:
   0.0 seconds (IMPORT FAILED): F:\comfyNodeGPT\ComfyUI\custom_nodes\NodeGPT
   0.3 seconds: F:\comfyNodeGPT\ComfyUI\custom_nodes\ComfyUI-Manager

Starting server

![image](https://github.com/xXAdonesXx/NodeGPT/assets/113643118/6150399d-17f1-4f43-aa10-b25eb94d90d8)

**Comment by angrysky56** [comment]
I needed cuda toolkit 11.8 oops. I may need to do a clean install though?

Error occurred when executing Chat:

(Deprecated) The autogen.Completion class requires openai<1 and diskcache.

File "F:\comfyNodeGPT\ComfyUI\execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\comfyNodeGPT\ComfyUI\execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\comfyNodeGPT\ComfyUI\execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\comfyNodeGPT\ComfyUI\custom_nodes\NodeGPT\Chat.py", line 53, in execute
autogen.ChatCompletion.start_logging(conversations)
File "F:\comfyNodeGPT\python_embeded\Lib\site-packages\autogen\oai\completion.py", line 1180, in start_logging
raise ERROR

**Comment by alenknight** [comment]
> I needed cuda toolkit 11.8 oops. I may need to do a clean install though?
> 
> Error occurred when executing Chat:
> 
> (Deprecated) The autogen.Completion class requires openai<1 and diskcache.
> 
> File "F:\comfyNodeGPT\ComfyUI\execution.py", line 153, in recursive_execute output_data, output_ui = get_output_data(obj, input_data_all) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "F:\comfyNodeGPT\ComfyUI\execution.py", line 83, in get_output_data return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "F:\comfyNodeGPT\ComfyUI\execution.py", line 76, in map_node_over_list results.append(getattr(obj, func)(**slice_dict(input_data_all, i))) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "F:\comfyNodeGPT\ComfyUI\custom_nodes\NodeGPT\Chat.py", line 53, in execute autogen.ChatCompletion.start_logging(conversations) File "F:\comfyNodeGPT\python_embeded\Lib\site-packages\autogen\oai\completion.py", line 1180, in start_logging raise ERROR

I'm getting this error too after update.  did you ever get this resolved?

**Comment by angrysky56** [comment]
Nope, really want to, but I finally found an autogen vid that could show how to hook to LM Studio properly along with MemGPT.

I tried setting autogen up on Docker like you are supposed to but failed due to not knowing crap about code, I got the container running but that was it lol.

I am pretty lost, but this vid could help a lot of folks and get this node working right if someone gets around to it.
https://www.youtube.com/watch?v=8RtxvXIx61Y
![Screenshot 2023-12-19 032742](https://github.com/xXAdonesXx/NodeGPT/assets/113643118/a70c35dc-2dc6-41b5-91fa-5881ddf5b9e4)

**Comment by angrysky56** [comment]
Also this is rad and I might run the API. If I can find a dev buddy to give me tips I imagine we could write our own nodes pretty easy:
https://www.youtube.com/watch?v=iwLe6UWyaS4

**Comment by daniel-lewis-ab** [comment]
AFAIK you seem to need a successful run of 

`pip install llama-cpp`
