### ISSUE TITLE
Error generating text: {"error":"This app has no endpoint /api/textgen/."}

### ISSUE THREAD

**Issue by xektop** [xXAdonesXx/NodeGPT#3]
Hi there,

could you please share a workflow.json from comfy as I can't make this work.
I get this error:
got prompt
Error generating text: {"error":"This app has no endpoint /api/textgen/."}
Traceback (most recent call last):
  File "G:\ComfyUI\ComfyUI\execution.py", line 184, in execute
    executed += recursive_execute(self.server, prompt, self.outputs, x, extra_data)
  File "G:\ComfyUI\ComfyUI\execution.py", line 62, in recursive_execute
    input_data_all = get_input_data(inputs, class_def, unique_id, outputs, prompt, extra_data)
  File "G:\ComfyUI\ComfyUI\execution.py", line 25, in get_input_data
    obj = outputs[input_unique_id][output_index]
KeyError: 0

MyComfy.bat is:
```
.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --listen
pause
```

My ooba bat is:
```
@echo off

@echo Starting the web UI...

cd /D "%~dp0"

set MAMBA_ROOT_PREFIX=%cd%\installer_files\mamba
set INSTALL_ENV_DIR=%cd%\installer_files\env

if not exist "%MAMBA_ROOT_PREFIX%\condabin\micromamba.bat" (
  call "%MAMBA_ROOT_PREFIX%\micromamba.exe" shell hook >nul 2>&1
)
call "%MAMBA_ROOT_PREFIX%\condabin\micromamba.bat" activate "%INSTALL_ENV_DIR%" || ( echo MicroMamba hook not found. && goto end )
cd text-generation-webui

call python server.py --auto-devices --chat --listen --no-stream --model vicuna-13b-GPTQ-4bit-128g --wbits 4 --groupsize 128 --model_type llama

:end
pause
```

Thank you in advance

**Comment by xektop** [comment]
removing the --chat started doing something... with other errors :D 

Oobabooga:
`Traceback (most recent call last):
  File "E:\ChatGPT\Oobaboga\installer_files\env\lib\site-packages\gradio\routes.py", line 395, in run_predict
    output = await app.get_blocks().process_api(
  File "E:\ChatGPT\Oobaboga\installer_files\env\lib\site-packages\gradio\blocks.py", line 1193, in process_api
    result = await self.call_function(
  File "E:\ChatGPT\Oobaboga\installer_files\env\lib\site-packages\gradio\blocks.py", line 930, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "E:\ChatGPT\Oobaboga\installer_files\env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\ChatGPT\Oobaboga\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\ChatGPT\Oobaboga\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "E:\ChatGPT\Oobaboga\installer_files\env\lib\site-packages\gradio\utils.py", line 491, in async_iteration
    return next(iterator)
  File "E:\ChatGPT\Oobaboga\text-generation-webui\modules\api.py", line 31, in generate_reply_wrapper
    for i in generate_reply(params[0], generate_params):
  File "E:\ChatGPT\Oobaboga\text-generation-webui\modules\text_generation.py", line 181, in generate_reply
    input_ids = encode(question, add_bos_token=state['add_bos_token'], truncation_length=get_max_prompt_length(state))
KeyError: 'add_bos_token'`

And ComfyUI:
`got prompt
Failed to validate prompt for output 14 Required input is missing. TextCombine, input_data_1
output will be ignored
Error generating text: {"error":null}
Traceback (most recent call last):
  File "G:\ComfyUI\ComfyUI\execution.py", line 184, in execute
    executed += recursive_execute(self.server, prompt, self.outputs, x, extra_data)
  File "G:\ComfyUI\ComfyUI\execution.py", line 62, in recursive_execute
    input_data_all = get_input_data(inputs, class_def, unique_id, outputs, prompt, extra_data)
  File "G:\ComfyUI\ComfyUI\execution.py", line 25, in get_input_data
    obj = outputs[input_unique_id][output_index]
KeyError: 0`

Still no clue what I am doing here :(

**Comment by xektop** [comment]
Guizmus was able to help me with this and actually the issue comes from oobabooga.
This is the hash for ooba that is working, if someone has the same issue:
git checkout 5543a5089d455708bae3b27e2461ac25e4482da6

**Comment by xXAdonesXx** [comment]
Can you try it with this code https://github.com/xXAdonesXx/NodeGPT/commit/c8cb3fa13d1645ea500767feca9cacd012fc863c ? Simply replace the content by copying and pasting the code into the Textnode.py file.
And for now just try to connect the InputText node with the GenerateText node with the OutputText node and check in your comfyUI folder if any text has been generated.

**Comment by xXAdonesXx** [comment]
commented to late :)
